### ISSUE TITLE
Please add a switch for 1-phase charging

### ISSUE THREAD

**Issue by DenBir** [mb-software/homeassistant-powerbrain#71]
The Power Brain Wallbox Solar use as default 3-phase charging and with a switch in the UI you can set to 1-phase charging.
It would be great if you add this switch in your HA Power Brain integration.

Thanks,
Dennis

**Comment by dylan09** [comment]
1+

**Comment by mb-software** [comment]
Hi,
unfortunately I do not own a powerbrain wallbox with the phase switching feature and have no possibility to develop and test it.
If anyone wants to contribute, please feel free.

**Comment by DenBir** [comment]
Hi @mb-software ,

I have a WB with phase switching (with the provided upgrade kit) but no knowlegde for Python.

Of course, I can provide you with the necessary information and then be happy to test it.

POST /cnf?cmd=set_device HTTP/1.1
Property: allow_ph_sw
Value: true / false
Property path: devices[0].allow_ph_sw
![2023-11-26 16_48_18-cFos Power Brain - Overview und 3 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/mb-software/homeassistant-powerbrain/assets/42352926/690fbbba-0fc1-4599-902b-614ac13f721a)

I found on the homepage the following guide https://www.cfos-emobility.de/en/cfos-charging-manager/documentation/automatic-phase-switching.htm

Set up an RFID for 3-phase charging in the user settings and set "Method" as the Charging Manager Output: GET and "URL" for this card:
http://localhost/cnf?cmd=modbus&device=evse&write=8087&value=0
For single-phase charging, you can set up an RFID card with Charging Manager Output "Method": GET and as "URL":
http://localhost/cnf?cmd=modbus&device=evse&write=8087&value=1
The prerequisite is that the wallbox runs as a master with activated load management.

and here the the necessary register 8087 https://www.cfos-emobility.de/en/cfos-power-brain/modbus-registers.htm

hth

**Comment by Frenchrapper** [comment]
For a phase switch you can add the following code to your configuration.yaml:

```
command_line:
  - switch:
      name: cfos_phase_switch
      command_on: "curl -s 'http://user:password@192.168.0.0/cnf?cmd=modbus&device=evse&write=8087&value=1'"
      command_off: "curl -s 'http://user_:password@192.168.0.0/cnf?cmd=modbus&device=evse&write=8087&value=0'"
```

You have to replace user (often admin), password and the IP adress.
After restart you will find a integration called "Command line" and there the entity "cfos_phase_switch".
On (=1) is 1-phase and off (=0) is 3-phase.
Yo can ckeck the state using the following URL: http://192.168.0.0/cnf?cmd=modbus&device=evse&read=8087

**Comment by bufu2012** [comment]
+1

**Comment by guibrazlima** [comment]
This has been implemented in PR #92.

A new `select` entity **Phase Mode** is added for each EVSE with options `1 phase` and `3 phases`. It uses Modbus register `8044` (used_phases bitfield: `1`=L1 only, `7`=L1+L2+L3).

There is also a new service `powerbrain.set_phase_mode` for use in automations:
```yaml
service: powerbrain.set_phase_mode
data:
  dev_id: E1
  phases: 1
```
