### ISSUE TITLE
SOC of battery

### ISSUE THREAD

**Issue by mtobehn** [mb-software/homeassistant-powerbrain#83]
Hello,
very nice project :-)
How can I import the SOC of a battery connected to a hybrid inverter?
Values for power, energy, current and voltage are available.

Thanks
Marco

**Comment by guibrazlima** [comment]
The `set_meter` service now supports a `soc` field (0–100%) for storage meters, addressed in PR #92.

You can send battery SOC from HA to the cFos Charging Manager like this:
```yaml
service: powerbrain.set_meter
data:
  dev_id: M1
  power: 500
  soc: 75
```
The `soc` value is passed directly to the `set_ajax_meter` API endpoint and can be used by the Charging Manager for solar surplus / storage-aware load balancing.
