### ISSUE TITLE
How to send meter readings from homeassistant to cFos Wallbox?

### ISSUE THREAD

**Issue by wmader23** [mb-software/homeassistant-powerbrain#89]
Modbus usually allows to connect a server to only one client. Such the case for my battery and my inverter.
I have all meter readings of battery and inverter integrated in homeassistant via the sunspec and varta (specific to my battery) integration.
The bullet point

"Adds a Homeassistant service to send power meter values to an HTTP input meter in the charging manager" 

from the README of this integration seems to indicate, that it can be used to sending meter readings from ha to the wallbox. However, I don't know how to do that.

If we can work this out together I will create a PR to update the documentation.

Thanks!

**Comment by dylan09** [comment]
I am sending my meter values via HTTP POST request using Node-Red. Should also be possible directly from HA.

```
http://CFOS-IP/cnf?cmd=set_ajax_meter&dev_id=M4
```

Take a look at the cFos documentation.

As I integrated my wallbox in HA Modbus integration inside cfos Wallbox wasn't working well. So I am stuck with HTTP requests.

**Comment by 98jan** [comment]
Hi @wmader23,

I am already using the REST endpoints of the cfos wallbox, which you could also reuse. This calls every 15 seconds (is the same interval as for modbus) the endpoint of the cfos wallbox and updates the meter values.

````YAML
# Configure RESTful Command
rest_command:
  send_wallbox_meter_data:
    # dev_id can differ
    url: http://<ip>/cnf?cmd=set_ajax_meter&dev_id=M4
    method: post
    username: <username>
    password: <password>>
    content_type: application/json
    # don't verify ssl as it's selfsigned
    verify_ssl: false
    # right now I am calculating the export/import of energy and sending to the wallbox, can also be splitted in different calls. You could just adapt this script.
    payload: '{ "power_w": {% if states("sensor.solax_grid_import") | float(default=0.0) - states("sensor.solax_battery_power_charge") | float(default=0.0) > 0 %} {{ states("sensor.solax_grid_import") | float(default=0.0) - states("sensor.solax_battery_power_charge") | float(default=0.0) }} {% else %} {{ states("sensor.solax_grid_export") | float(default=0.0) | multiply(-1) }} {% endif %} }'
    # '{ "power_w": {{ states("sensor.solax_grid_export") | float(default=0.0) | multiply(-1) }} }'
    #payload: '{ "export_wh": {{ states("sensor.solax_grid_export") }}, "current": [{{ states("sensor.solax_inverter_current_l1") | float(default=0.0) | multiply(1000)}}, {{ states("sensor.solax_inverter_current_l2") | float(default=0.0) | multiply(1000)}}, {{states("sensor.solax_inverter_current_l3") | float(default=0.0) | multiply(1000)}}]}'

automation:
  - alias: "Send Data to Wallbox"
    trigger:
      platform: time_pattern
      seconds: "/15"
    action:
      service: rest_command.send_wallbox_meter_data
```

**Comment by wmader23** [comment]
Hei, thank your for the code snipped!

**Comment by Thinky-123** [comment]
Hi,

thanks for building the homeassistant integration.
There is an action powerbrain.set_meter. Testing is possible under Developer Tools > Actions
Parameters are also listed there, but I think it doesn't work anymore. My cFos Power Brain only reacts to"power**_w**" instead of "power". Parameter seems to be changed in year 2023 by cfos.
@mb-software Can you update the code?

**Comment by guibrazlima** [comment]
The `set_meter` service does exactly this. PR #92 adds proper documentation in the README.

Example — send readings from a HA sensor to cFos HTTP input meter `M1`:
```yaml
service: powerbrain.set_meter
data:
  dev_id: M1
  power: "{{ states('sensor.battery_power') | int }}"
  import_energy: "{{ states('sensor.battery_import_energy') | float }}"
  export_energy: "{{ states('sensor.battery_export_energy') | float }}"
  current_l1: "{{ states('sensor.battery_current_l1') | float }}"
  voltage_l1: 230
```
Make sure the meter in cFos is set to type **HTTP Input**.
